# -*- coding: utf-8 -*-
"""Spinaker_Embeddings and semantic similarity in business application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWCX76ruhnl3pzQTU28emi310SorKm9a

# Embeddings and Semantic Similarity in Business Applications

In this notebook, we will work with **sentence embeddings**.

Sentence embeddings are numerical representations of entire pieces of text, such as customer reviews, support tickets, emails, or survey responses.

The key idea is that texts with similar meanings should have similar vector representations, even if they use different words.

For example:

> "I received the wrong invoice."  
> "There was a billing mistake on my account."

These sentences use different words, but they describe a similar business issue. A good embedding model should place them close together in the vector space.

In this notebook, we will demonstrate:

- How business texts can be represented as vectors
- How semantic similarity is measured
- How semantic search works
- How customer feedback can be categorized
- How embeddings can support business decision-making


Unlike keyword search, embeddings allow us to search by **meaning** rather than exact words. This makes them particularly useful for customer feedback analysis, support automation, document retrieval, and knowledge management.

**Loading a Pre-trained Sentence Transformer Model**

We will use a pre-trained Sentence Transformer model. The model all-MiniLM-L6-v2 was trained on large collections of text and produces a 384-dimensional vector for each sentence.


We do not train the model ourselves - we load a model that has already learned semantic relationships between texts.


Instead of generating vectors for individual words like GloVe embedding, we generate vectors for complete sentences.
"""

!pip install -q pandas scikit-learn sentence-transformers matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("all-MiniLM-L6-v2")

"""# Business Dataset

Suppose we collected customer feedback from an e-commerce company.

Each review contains information about customer experiences with:

- Deliveries
- Invoices
- Payments
- Support
- Mobile applications
"""

# Imagine these are customer reviews collected from a post-purchase survey.

reviews = [
    "The delivery was fast and the product quality exceeded my expectations.",
    "Customer support ignored my complaint for five days.",
    "The mobile app is easy to use, but the payment screen crashes.",
    "The price is competitive, although delivery could be faster.",
    "I received the wrong invoice and nobody explained the issue.",
    "Premium support solved my problem in less than one hour.",
    "The checkout process failed when I tried to pay by credit card.",
    "The package arrived late and the tracking information was unclear.",
    "I was charged twice for the same order.",
    "The chatbot gave helpful answers about my return request."
]

df = pd.DataFrame({"review": reviews})

# Simple metadata can help business users understand the dataset.
df["text_length"] = df["review"].str.len()
df["word_count"] = df["review"].str.split().str.len()

df

"""# Convert business texts into embeddings"""

# Similar texts should have similar vectors, even if they use different words.

embeddings = model.encode(
    reviews,
    normalize_embeddings=True
)

print("Number of reviews:", len(reviews))
print("Embedding shape:", embeddings.shape)
print("Each review is represented by", embeddings.shape[1], "numbers.")

"""# Semantic similarity matrix"""

# Cosine similarity measures how close two embeddings are.
#
# Score interpretation:
# - close to 1.0: very similar meaning
# - around 0.5: somewhat related
# - close to 0.0: weakly related
# - negative: usually unrelated/opposite in embedding space

similarity_matrix = cosine_similarity(embeddings)

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=[f"Review {i+1}" for i in range(len(reviews))],
    columns=[f"Review {i+1}" for i in range(len(reviews))]
)

similarity_df.round(2)

# Display the original review IDs for easier interpretation.

review_lookup = pd.DataFrame({
    "review_id": [f"Review {i+1}" for i in range(len(reviews))],
    "review": reviews
})

review_lookup

"""# Visualize semantic similarity"""

# This heatmap helps to see
# which pieces of feedback are semantically close to each other.

plt.figure(figsize=(9, 7))
plt.imshow(similarity_matrix)
plt.colorbar(label="Cosine similarity")
plt.xticks(range(len(reviews)), [f"R{i+1}" for i in range(len(reviews))], rotation=45)
plt.yticks(range(len(reviews)), [f"R{i+1}" for i in range(len(reviews))])
plt.title("Semantic Similarity Between Customer Reviews")
plt.show()

"""# Semantic search: find reviews related to a business problem"""

# Traditional keyword search may miss relevant reviews.
# Example:
# Query: "billing problem with invoice"
# This should find reviews about invoices, charges, payment, and billing,
# even if the exact word "billing" does not appear.

query = "billing problem with invoice"

query_embedding = model.encode(
    [query],
    normalize_embeddings=True
)

scores = cosine_similarity(query_embedding, embeddings)[0]

results = pd.DataFrame({
    "review": reviews,
    "similarity_score": scores
}).sort_values("similarity_score", ascending=False)

results.round(3)

"""# Make results easier for business users to read"""

def semantic_search(query, texts, embeddings, model, top_k=5):
    """
    Search for the most semantically similar texts.

    Parameters
    ----------
    query : str
        Business question or issue, e.g. "payment failed".
    texts : list[str]
        Documents, reviews, tickets, or comments.
    embeddings : np.ndarray
        Precomputed embeddings for texts.
    model : SentenceTransformer
        Local embedding model.
    top_k : int
        Number of most relevant results to return.

    Returns
    -------
    pd.DataFrame
        Ranked results with similarity scores.
    """

    query_embedding = model.encode(
        [query],
        normalize_embeddings=True
    )

    similarity_scores = cosine_similarity(query_embedding, embeddings)[0]

    result_df = pd.DataFrame({
        "rank": range(1, len(texts) + 1),
        "review": texts,
        "similarity_score": similarity_scores
    })

    result_df = result_df.sort_values(
        "similarity_score",
        ascending=False
    ).head(top_k)

    result_df["rank"] = range(1, len(result_df) + 1)

    return result_df


semantic_search(
    query="customers having problems with payments",
    texts=reviews,
    embeddings=embeddings,
    model=model,
    top_k=5
).round(3)

"""# Compare keyword search vs semantic search"""

# keyword search only finds exact words,
# while embeddings find meaning.

def keyword_search(keyword, texts):
    """
    Very simple keyword search.
    """
    keyword = keyword.lower()

    matches = [
        text for text in texts
        if keyword in text.lower()
    ]

    return pd.DataFrame({"keyword_match": matches})


print("Keyword search for 'billing':")
display(keyword_search("billing", reviews))

print("Semantic search for 'billing problem':")
display(
    semantic_search(
        query="billing problem",
        texts=reviews,
        embeddings=embeddings,
        model=model,
        top_k=5
    ).round(3)
)

"""# Business category detection using semantic similarity"""

# We can classify feedback into business themes without training a model.
# This is useful when you have no labeled dataset.

business_categories = {
    "Delivery and logistics": "late delivery, slow shipping, tracking problem, package issue",
    "Billing and invoices": "wrong invoice, payment problem, overcharged, charged twice",
    "Customer support": "support ignored complaint, slow response, helpful support",
    "App and checkout experience": "mobile app crash, checkout failed, payment screen problem",
    "Pricing and value": "price, discount, competitive pricing, expensive product"
}

category_names = list(business_categories.keys())
category_descriptions = list(business_categories.values())

category_embeddings = model.encode(
    category_descriptions,
    normalize_embeddings=True
)

category_scores = cosine_similarity(embeddings, category_embeddings)

predicted_category_index = np.argmax(category_scores, axis=1)
predicted_category_score = np.max(category_scores, axis=1)

df["predicted_category"] = [
    category_names[i] for i in predicted_category_index
]

df["category_confidence"] = predicted_category_score

df[["review", "predicted_category", "category_confidence"]].round(3)

"""# Summarize business insights"""

# This converts embeddings into something useful for managers:
# "What are customers talking about most?"

category_summary = (
    df.groupby("predicted_category")
    .agg(
        number_of_reviews=("review", "count"),
        average_confidence=("category_confidence", "mean")
    )
    .sort_values("number_of_reviews", ascending=False)
)

category_summary.round(3)

# Simple bar chart for visualization

category_summary["number_of_reviews"].plot(kind="bar", figsize=(8, 4))

plt.title("Main Customer Feedback Themes")
plt.xlabel("Business category")
plt.ylabel("Number of reviews")
plt.xticks(rotation=45, ha="right")
plt.show()

"""# Find duplicates or near-duplicates"""

# Detect repeated complaints, repeated support tickets,
# or similar customer issues across channels.

pairs = []

for i in range(len(reviews)):
    for j in range(i + 1, len(reviews)):
        pairs.append({
            "review_1": reviews[i],
            "review_2": reviews[j],
            "similarity": similarity_matrix[i, j]
        })

similar_pairs = (
    pd.DataFrame(pairs)
    .sort_values("similarity", ascending=False)
)

similar_pairs.head(10).round(3)

"""# Business interpretation"""

# Similarity scores help prioritize what humans should inspect first.

def interpret_similarity(score):
    if score >= 0.70:
        return "Very similar"
    elif score >= 0.50:
        return "Related"
    elif score >= 0.30:
        return "Weakly related"
    else:
        return "Probably unrelated"


similar_pairs["interpretation"] = similar_pairs["similarity"].apply(interpret_similarity)

similar_pairs.head(10).round(3)

"""# TASK
Try your own business queries.

Suggested queries:
- "payment and checkout problems"
- "customers complain about slow support"
- "delivery delays"
- "positive support experience"
- "pricing concerns"
"""

# For example:
query = "payment and checkout problems"

semantic_search(
    query=query,
    texts=reviews,
    embeddings=embeddings,
    model=model,
    top_k=5
).round(3)